---
# http://module-build.sourceforge.net/META-spec.html
name:         Business-BR-Ids
version:      0.00_15
version_from: lib/Business/BR/Ids.pm
author:
  - Adriano Ferreira <ferreira@cpan.org>
license: perl
requires:
    Scalar::Util:                  0
    Test::More:                    0
installdirs:  site

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
