--- #YAML:1.0
name:                Business-BR-Ids
version:             0.00_19
abstract:            Modules for dealing with Brazilian identification codes (CPF, CNPJ, ...)
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Scalar::Util:                  1.11
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - A. R. Ferreira <ferreira@cpan.org>
